# Generated by Django 5.2.16 on 2026-07-26 14:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Например: protocol_interrogation, indictment', unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название вида документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид документа',
                'verbose_name_plural': 'Виды документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('rank', models.CharField(blank=True, max_length=100, verbose_name='Звание/Чин')),
                ('initials', models.CharField(blank=True, max_length=20, verbose_name='Инициалы')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('address', models.TextField(verbose_name='Адрес проживания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('marital_status', models.CharField(max_length=50, verbose_name='Семейное положение')),
                ('employment', models.CharField(max_length=255, verbose_name='Место работы/учебы')),
                ('work_phone', models.CharField(max_length=20, verbose_name='Рабочий телефон')),
                ('military_duty', models.CharField(max_length=100, verbose_name='Отношение к воинской обязанности')),
                ('criminal_record', models.TextField(verbose_name='Наличие судимости')),
                ('document_type', models.CharField(max_length=100, verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('signature', models.CharField(max_length=100, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Участник уголовного дела',
                'verbose_name_plural': 'Участники уголовного дела',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов к подписанию'), ('signed', 'Подписан'), ('sent', 'Направлен'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адрес проживания')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('object_description', models.TextField(blank=True, null=True)),
                ('target_action', models.CharField(blank=True, max_length=255, null=True)),
                ('items_found', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов к подписанию'), ('signed', 'Подписан'), ('sent', 'Направлен'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('case_date', models.DateField(verbose_name='Дата дела')),
                ('case_number', models.CharField(max_length=100, verbose_name='Номер уголовного дела')),
                ('article_uk_rf', models.CharField(max_length=100, verbose_name='Статья УК РФ')),
                ('file_path', models.FilePathField(blank=True, null=True, path='media/documents', verbose_name='Путь к файлу .docx')),
                ('content', models.TextField(blank=True, verbose_name='Содержание документа')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='Дата составления документа')),
                ('creator_full_name', models.CharField(max_length=255, verbose_name='ФИО составителя')),
                ('recipient_position', models.CharField(max_length=255, verbose_name='Должность получателя')),
                ('information_source', models.TextField(verbose_name='Источник получения информации')),
                ('crime_description', models.TextField(blank=True, verbose_name='Описание преступления')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='Куда направляется')),
                ('items_seized', models.TextField(blank=True, verbose_name='Что изъято')),
                ('statements', models.TextField(blank=True, verbose_name='Заявления')),
                ('tech_equipment', models.TextField(blank=True, verbose_name='Техсредства')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('to_do', models.TextField(blank=True, verbose_name='Что необходимо / выполнено')),
                ('location', models.CharField(max_length=255, verbose_name='Место составления')),
                ('place', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('authority_name', models.CharField(max_length=255, verbose_name='Наименование органа')),
                ('recorded_correctly', models.CharField(max_length=50, verbose_name='Запись соответствует')),
                ('investigation_circumstances', models.TextField(blank=True, verbose_name='Обстоятельства расследования')),
                ('required_actions', models.TextField(blank=True, verbose_name='Необходимые действия')),
                ('attachments', models.TextField(blank=True, verbose_name='Приложения')),
                ('message_from', models.CharField(blank=True, max_length=255, verbose_name='От кого получено сообщение')),
                ('message_about', models.TextField(blank=True, verbose_name='О чем получено сообщение')),
                ('arrived_to', models.CharField(blank=True, max_length=255, verbose_name='Место прибытия')),
                ('other_participants', models.TextField(blank=True, verbose_name='Иные участвующие лица')),
                ('weather_conditions', models.CharField(blank=True, max_length=100, verbose_name='Погодные условия')),
                ('lighting_conditions', models.CharField(blank=True, max_length=100, verbose_name='Условия освещенности')),
                ('technical_means', models.TextField(blank=True, verbose_name='Технические средства')),
                ('object_inspection', models.TextField(blank=True, verbose_name='Объект осмотра')),
                ('inspection_results', models.TextField(blank=True, verbose_name='Результаты осмотра')),
                ('examination_methods', models.TextField(blank=True, verbose_name='Методы исследования')),
                ('seized_items', models.TextField(blank=True, verbose_name='Изъятые предметы')),
                ('reading_method', models.CharField(blank=True, max_length=100, verbose_name='Способ ознакомления')),
                ('remarks', models.TextField(blank=True, verbose_name='Замечания участников')),
                ('witness1_signature', models.CharField(blank=True, max_length=50, verbose_name='Подпись понятого 1')),
                ('witness2_signature', models.CharField(blank=True, max_length=50, verbose_name='Подпись понятого 2')),
                ('specialist_signature', models.CharField(blank=True, max_length=50, verbose_name='Подпись специалиста')),
                ('other_participants_signatures', models.TextField(blank=True, verbose_name='Подписи иных участников')),
                ('investigator_signature', models.CharField(blank=True, max_length=50, verbose_name='Подпись следователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='Вид документа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='documents.employee')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.employee', verbose_name='Следователь')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.participant', verbose_name='Кто составил / участник')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.specialist', verbose_name='Специалист')),
                ('witness1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_as_witness1', to='documents.witness', verbose_name='Понятой 1')),
                ('witness2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_as_witness2', to='documents.witness', verbose_name='Понятой 2')),
            ],
            options={
                'verbose_name': 'Уголовно‑процессуальный документ',
                'verbose_name_plural': 'Уголовно‑процессуальные документы',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
