# Generated by Django 5.2.16 on 2026-07-30 11:24

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_created',
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('suspect', 'Подозреваемый'), ('OUR', 'Оперуполномоченный'), ('victim', 'Потерпевший'), ('witness', 'Понятой'), ('lawyer', 'Защитник (адвокат)'), ('investigator', 'Следователь'), ('UUP', 'Участковый уполномоченный'), ('expert', 'Эксперт'), ('other', 'Иное лицо')], default='other', max_length=50, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='participant',
            name='side',
            field=models.CharField(choices=[('prosecution', 'Сторона обвинения'), ('defense', 'Сторона защиты'), ('other', 'Иные лица')], default='other', max_length=50, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(default=documents.models.default_issue_date, verbose_name='Дата составления документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='items_found',
            field=models.TextField(blank=True, null=True, verbose_name='Обнаруженные предметы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='object_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание объекта'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reason',
            field=models.TextField(verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='target_action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Целевое действие'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
