# Generated by Django 5.2.16 on 2026-07-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_date_created_participant_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
