# Generated by Django 5.2.16 on 2026-08-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_participant_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.AlterField(
            model_name='document',
            name='investigator',
            field=models.ForeignKey(limit_choices_to={'role': 'investigator'}, on_delete=django.db.models.deletion.PROTECT, related_name='documents_authored', to='documents.participant', verbose_name='Следователь (автор)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='specialist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'expert'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_as_specialist', to='documents.participant', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='document',
            name='witness1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_as_witness1', to='documents.participant', verbose_name='Понятой 1'),
        ),
        migrations.AlterField(
            model_name='document',
            name='witness2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_as_witness2', to='documents.participant', verbose_name='Понятой 2'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='address',
        ),
        migrations.AlterField(
            model_name='document',
            name='authority_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование органа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creator_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО составителя'),
        ),
        migrations.AlterField(
            model_name='document',
            name='information_source',
            field=models.TextField(blank=True, verbose_name='Источник получения информации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место составления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_as_main_participant', to='documents.participant', verbose_name='Основной участник'),
        ),
        migrations.AlterField(
            model_name='document',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Основание / причина'),
        ),
        migrations.AlterField(
            model_name='document',
            name='recipient_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность получателя'),
        ),
        migrations.AlterField(
            model_name='document',
            name='recorded_correctly',
            field=models.CharField(blank=True, max_length=50, verbose_name='Запись соответствует'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.SlugField(help_text='Например: explanation, inspection_protokol, voluntary_surrender, orm_instruction', unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='criminal_record',
            field=models.TextField(blank=True, verbose_name='Наличие судимости'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='education',
            field=models.CharField(blank=True, max_length=100, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='employment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы/учёбы'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='military_duty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отношение к воинской обязанности'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='signature',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.DeleteModel(
            name='Witness',
        ),
    ]
