# Generated by Django 5.2.16 on 2026-08-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_author_alter_document_investigator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
