# Generated by Django 5.2.16 on 2026-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['phone'], name='documents_p_phone_2527ab_idx'),
        ),
    ]
