# Generated by Django 5.2.16 on 2026-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность / позиция'),
        ),
    ]
