# Generated by Django 5.2.16 on 2026-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_participant_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
