# Generated by Django 5.2.16 on 2026-08-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_investigator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investigator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='reading_method',
        ),
        migrations.RemoveField(
            model_name='document',
            name='recorded_correctly',
        ),
        migrations.AddField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
