# Generated by Django 5.2.16 on 2026-07-26 14:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='read_method',
        ),
        migrations.AlterField(
            model_name='document',
            name='arrived_to',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место прибытия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='case_number',
            field=models.CharField(max_length=100, verbose_name='Номер уголовного дела'),
        ),
        migrations.AlterField(
            model_name='document',
            name='crime_description',
            field=models.TextField(blank=True, verbose_name='Описание преступления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='examination_methods',
            field=models.TextField(blank=True, verbose_name='Методы исследования'),
        ),
        migrations.AlterField(
            model_name='document',
            name='inspection_results',
            field=models.TextField(blank=True, verbose_name='Результаты осмотра'),
        ),
        migrations.AlterField(
            model_name='document',
            name='investigation_circumstances',
            field=models.TextField(blank=True, verbose_name='Обстоятельства расследования'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата составления документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='lighting_conditions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Условия освещенности'),
        ),
        migrations.AlterField(
            model_name='document',
            name='message_about',
            field=models.TextField(blank=True, verbose_name='О чем получено сообщение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='message_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='От кого получено сообщение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='object_inspection',
            field=models.TextField(blank=True, verbose_name='Объект осмотра'),
        ),
        migrations.AlterField(
            model_name='document',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='procedure.participant', verbose_name='Кто составил / участник'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reading_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Способ ознакомления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='required_actions',
            field=models.TextField(blank=True, verbose_name='Необходимые действия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='seized_items',
            field=models.TextField(blank=True, verbose_name='Изъятые предметы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procedure.specialist', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='document',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='document',
            name='technical_means',
            field=models.TextField(blank=True, verbose_name='Технические средства'),
        ),
        migrations.AlterField(
            model_name='document',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='document',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Погодные условия'),
        ),
    ]
